### ==========================================================
### 08. 수료증 PDF 발급
### 먼저 01-auth-map.http에서 로그인 실행 후 사용
###
### 조건:
### - 강의 이수 완료 내역 존재
### ==========================================================


### 수료증 - PDF 발급
GET http://localhost:15000/api/v1/courses/3/certificate
Authorization: Bearer {{userAccessToken}}
