title: "[TODO] "
body:
  - type: textarea
    id: name1
    attributes:
      label: 김진도
    validations:
      required: false

  - type: textarea
    id: name2
    attributes:
      label: 고성민
    validations:
      required: false

  - type: textarea
    id: name3
    attributes:
      label: 백승재
    validations:
      required: false

  - type: textarea
    id: name4
    attributes:
      label: 이채연
    validations:
      required: false

  - type: textarea
    id: name5
    attributes:
      label: 이하연
    validations:
      required: false
