spring:
  application:
    name: algoga_server

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  config:
    import:
      - optional:classpath:/domains/banner.yml
      - optional:classpath:/domains/userProfile.yml

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 15000
  forward-headers-strategy: native

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  default-produces-media-type: application/json

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 1800000 # 30분
  refresh-token-expiration: 604800000 # 7일

app:
  file:
    upload-root: uploads

portone:
  base-url: ${PORTONE_BASE_URL}
  store-id: ${PORTONE_STORE_ID}
  api-secret: ${PORTONE_API_SECRET}
  channel-key: ${PORTONE_CHANNEL_KEY}

cloud:
  aws:
    s3:
      endpoint: ${S3_ENDPOINT}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2

flight:
  api:
    base-url: ${FLIGHT_BASE_URL}
    service-key: ${FLIGHT_API_SERVICE_KEY}

user:
  storage:
    bucket: algoga-banner
    directory: profiles