### ==========================================================
### 01. 인증 + 지도/국가별 강의 조회
### 사용 순서:
### 1) 로그인 실행
### 2) accessToken 저장 확인
### 3) 아래 지도/국가별 강의 조회 실행
### ==========================================================


### 회원가입
### 이미 가입된 계정이면 건너뛰어도 됨
POST http://localhost:15000/api/v1/auth/signup
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "email": "testuser88@algoga.com",
  "password": "password12345",
  "name": "윤라프",
  "phone": "010-8888-9999",
  "birthDate": "2022-01-26",
  "gender": "MALE",
  "nickname": "윤라프개귀여워",
  "referralCode": "REF003",
  "signupPath": "인스타그램"
}


### 로그인
### 실행하면 accessToken, refreshToken이 IntelliJ 전역 변수로 저장됨
POST http://localhost:15000/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "password12345"
}

> {%
    if (response.status === 200) {
        client.global.set("accessToken", response.body.data.accessToken);
        client.global.set("refreshToken", response.body.data.refreshToken);
        client.log("Access Token 저장 완료: " + client.global.get("accessToken"));
    }
%}


### ----------------------------------------------------------
### 지도 - 대륙 목록 조회
GET http://localhost:15000/api/v1/maps/continents
Authorization: Bearer {{accessToken}}


### 지도 - 아시아 국가 목록 조회
GET http://localhost:15000/api/v1/maps/continents/ASIA/countries
Authorization: Bearer {{accessToken}}


### 지도 - 유럽 국가 목록 조회
GET http://localhost:15000/api/v1/maps/continents/EUROPE/countries
Authorization: Bearer {{accessToken}}


### 국가별 강의 목록 조회 - 일본
GET http://localhost:15000/api/v1/courses/countries/1
Authorization: Bearer {{accessToken}}