### =========================================
### 🌟 [이메일 인증 테스트]
### =========================================

### 1. 이메일 인증번호 발송 요청
# 메일을 확인할 수 있는 '진짜 이메일'을 적어주세요!
POST http://localhost:15000/api/v1/auth/email/send-code
Content-Type: application/json

{
  "email": "mac0616@naver.com"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### 2. 이메일 인증번호 확인
# 💡 위 API를 실행하고 실제 메일함으로 날아온 6자리 숫자를 "code"에 적고 실행하세요!
POST http://localhost:15000/api/v1/auth/email/verify-code
Content-Type: application/json

{
  "email": "mac0616@naver.com",
  "code": "551305"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### 3. 회원가입 (이메일 인증 완료 후 진행)
POST http://localhost:15000/api/v1/auth/signup
Content-Type: application/json
Accept: application/json

{
  "username": "welcomecoupontest4",
  "email": "mac0616@naver.com",
  "password": "test1234",
  "name": "새가입4",
  "phone": "010-3444-9090",
  "birthDate": "2000-03-02",
  "gender": "FEMALE",
  "nickname": "가입시쿠폰",
  "referralCode": "REF008",
  "signupPath": "인스타그램",
  "termsServiceAgreed": true,
  "termsPrivacyAgreed": true,
  "termsMarketingAgreed": false
}

> {%
    client.test("회원가입 성공 여부 확인", function() {
        client.assert(response.status === 201, "상태 코드가 201이 아닙니다.");
        client.log("응답 메시지: " + response.body.message);
    });
%}

### 로그인
POST http://localhost:15000/api/v1/auth/login
Content-Type: application/json

{
  "username": "welcomecoupontest4",
  "password": "test1234"
}

> {%
    client.test("로그인 성공 및 토큰 저장", function() {
        client.assert(response.status === 200, "상태 코드가 200이 아닙니다.");
        client.global.set("userAccessToken", response.body.data.accessToken);
        client.global.set("userRefreshToken", response.body.data.refreshToken);
        client.log("User Access Token 저장 완료: " + client.global.get("userAccessToken"));
    });
%}

### 내 쿠폰 조회
GET http://localhost:15000/api/v1/my/benefits/coupons
Authorization: Bearer {{userAccessToken}}

### 내 마일리지 조회
GET http://localhost:15000/api/v1/my/benefits/mileages
Authorization: Bearer {{userAccessToken}}
Accept: application/json


### 쿠폰 삭제
DELETE http://localhost:15000/api/v1/admin/courses/3/coupon-policies/12
Authorization: Bearer {{managerAccessToken}}
Accept: application/json