global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'algoga-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:15000'] # Docker에서 호스트 PC의 Spring Boot 접근